# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mc_main.ui'
#
# Created: Wed Mar  4 14:29:05 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mc_main(object):
    def setupUi(self, mc_main):
        mc_main.setObjectName("mc_main")
        mc_main.resize(657, 736)
        self.centralWidget = QtGui.QWidget(mc_main)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sheetBox = QtGui.QGroupBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sheetBox.sizePolicy().hasHeightForWidth())
        self.sheetBox.setSizePolicy(sizePolicy)
        self.sheetBox.setObjectName("sheetBox")
        self.gridLayout = QtGui.QGridLayout(self.sheetBox)
        self.gridLayout.setObjectName("gridLayout")
        self.fileDirT = QtGui.QCheckBox(self.sheetBox)
        self.fileDirT.setChecked(True)
        self.fileDirT.setObjectName("fileDirT")
        self.gridLayout.addWidget(self.fileDirT, 1, 2, 1, 1)
        self.fileDirL = QtGui.QLabel(self.sheetBox)
        self.fileDirL.setObjectName("fileDirL")
        self.gridLayout.addWidget(self.fileDirL, 1, 0, 1, 1)
        self.fileQualL = QtGui.QLabel(self.sheetBox)
        self.fileQualL.setObjectName("fileQualL")
        self.gridLayout.addWidget(self.fileQualL, 2, 0, 1, 1)
        self.fileOrderC = QtGui.QComboBox(self.sheetBox)
        self.fileOrderC.setObjectName("fileOrderC")
        self.fileOrderC.addItem("")
        self.fileOrderC.addItem("")
        self.gridLayout.addWidget(self.fileOrderC, 8, 1, 1, 1)
        self.fileWidthL = QtGui.QLabel(self.sheetBox)
        self.fileWidthL.setObjectName("fileWidthL")
        self.gridLayout.addWidget(self.fileWidthL, 3, 0, 1, 1)
        self.fileHeightE = QtGui.QLineEdit(self.sheetBox)
        self.fileHeightE.setEnabled(False)
        self.fileHeightE.setText("")
        self.fileHeightE.setObjectName("fileHeightE")
        self.gridLayout.addWidget(self.fileHeightE, 4, 1, 1, 1)
        self.fileQualE = QtGui.QLineEdit(self.sheetBox)
        self.fileQualE.setObjectName("fileQualE")
        self.gridLayout.addWidget(self.fileQualE, 2, 1, 1, 1)
        self.fileOverwriteL = QtGui.QLabel(self.sheetBox)
        self.fileOverwriteL.setObjectName("fileOverwriteL")
        self.gridLayout.addWidget(self.fileOverwriteL, 7, 0, 1, 1)
        self.fileHeightT = QtGui.QCheckBox(self.sheetBox)
        self.fileHeightT.setChecked(True)
        self.fileHeightT.setObjectName("fileHeightT")
        self.gridLayout.addWidget(self.fileHeightT, 4, 2, 1, 1)
        self.fileOrderL = QtGui.QLabel(self.sheetBox)
        self.fileOrderL.setObjectName("fileOrderL")
        self.gridLayout.addWidget(self.fileOrderL, 8, 0, 1, 1)
        self.fileExtE = QtGui.QLineEdit(self.sheetBox)
        self.fileExtE.setObjectName("fileExtE")
        self.gridLayout.addWidget(self.fileExtE, 0, 1, 1, 1)
        self.fileWidthE = QtGui.QLineEdit(self.sheetBox)
        self.fileWidthE.setObjectName("fileWidthE")
        self.gridLayout.addWidget(self.fileWidthE, 3, 1, 1, 1)
        self.fileBackgroundL = QtGui.QLabel(self.sheetBox)
        self.fileBackgroundL.setObjectName("fileBackgroundL")
        self.gridLayout.addWidget(self.fileBackgroundL, 5, 0, 1, 1)
        self.fileHeightL = QtGui.QLabel(self.sheetBox)
        self.fileHeightL.setObjectName("fileHeightL")
        self.gridLayout.addWidget(self.fileHeightL, 4, 0, 1, 1)
        self.fileExtL = QtGui.QLabel(self.sheetBox)
        self.fileExtL.setObjectName("fileExtL")
        self.gridLayout.addWidget(self.fileExtL, 0, 0, 1, 1)
        self.fileOverwriteC = QtGui.QComboBox(self.sheetBox)
        self.fileOverwriteC.setObjectName("fileOverwriteC")
        self.fileOverwriteC.addItem("")
        self.fileOverwriteC.addItem("")
        self.gridLayout.addWidget(self.fileOverwriteC, 7, 1, 1, 1)
        self.fileBackgroundB = QtGui.QPushButton(self.sheetBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.fileBackgroundB.setPalette(palette)
        self.fileBackgroundB.setText("")
        self.fileBackgroundB.setObjectName("fileBackgroundB")
        self.gridLayout.addWidget(self.fileBackgroundB, 5, 1, 1, 1)
        self.fileDirE = QtGui.QPushButton(self.sheetBox)
        self.fileDirE.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.fileDirE.setPalette(palette)
        self.fileDirE.setText("")
        self.fileDirE.setObjectName("fileDirE")
        self.gridLayout.addWidget(self.fileDirE, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.sheetBox, 0, 0, 1, 1)
        self.thumbBox = QtGui.QGroupBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbBox.sizePolicy().hasHeightForWidth())
        self.thumbBox.setSizePolicy(sizePolicy)
        self.thumbBox.setObjectName("thumbBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.thumbBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.thumbHeightL = QtGui.QLabel(self.thumbBox)
        self.thumbHeightL.setObjectName("thumbHeightL")
        self.gridLayout_2.addWidget(self.thumbHeightL, 0, 0, 1, 1)
        self.thumbHeightE = QtGui.QLineEdit(self.thumbBox)
        self.thumbHeightE.setObjectName("thumbHeightE")
        self.gridLayout_2.addWidget(self.thumbHeightE, 0, 1, 1, 1)
        self.thumbBorderL = QtGui.QLabel(self.thumbBox)
        self.thumbBorderL.setObjectName("thumbBorderL")
        self.gridLayout_2.addWidget(self.thumbBorderL, 1, 0, 1, 1)
        self.thumbBorderE = QtGui.QLineEdit(self.thumbBox)
        self.thumbBorderE.setObjectName("thumbBorderE")
        self.gridLayout_2.addWidget(self.thumbBorderE, 1, 1, 1, 1)
        self.thumbCoverModeL = QtGui.QLabel(self.thumbBox)
        self.thumbCoverModeL.setObjectName("thumbCoverModeL")
        self.gridLayout_2.addWidget(self.thumbCoverModeL, 2, 0, 1, 1)
        self.thumbCoverModeC = QtGui.QComboBox(self.thumbBox)
        self.thumbCoverModeC.setObjectName("thumbCoverModeC")
        self.thumbCoverModeC.addItem("")
        self.thumbCoverModeC.addItem("")
        self.thumbCoverModeC.addItem("")
        self.gridLayout_2.addWidget(self.thumbCoverModeC, 2, 1, 1, 1)
        self.thumbCoverL = QtGui.QLabel(self.thumbBox)
        self.thumbCoverL.setObjectName("thumbCoverL")
        self.gridLayout_2.addWidget(self.thumbCoverL, 3, 0, 1, 1)
        self.thumbCoverE = QtGui.QLineEdit(self.thumbBox)
        self.thumbCoverE.setText("")
        self.thumbCoverE.setObjectName("thumbCoverE")
        self.gridLayout_2.addWidget(self.thumbCoverE, 3, 1, 1, 1)
        self.thumbCoverScaleL = QtGui.QLabel(self.thumbBox)
        self.thumbCoverScaleL.setObjectName("thumbCoverScaleL")
        self.gridLayout_2.addWidget(self.thumbCoverScaleL, 4, 0, 1, 1)
        self.thumbCoverScaleS = QtGui.QComboBox(self.thumbBox)
        self.thumbCoverScaleS.setObjectName("thumbCoverScaleS")
        self.thumbCoverScaleS.addItem("")
        self.thumbCoverScaleS.addItem("")
        self.thumbCoverScaleS.addItem("")
        self.thumbCoverScaleS.addItem("")
        self.thumbCoverScaleS.addItem("")
        self.thumbCoverScaleS.addItem("")
        self.gridLayout_2.addWidget(self.thumbCoverScaleS, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.thumbBox, 0, 1, 1, 1)
        self.titleBox = QtGui.QGroupBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleBox.sizePolicy().hasHeightForWidth())
        self.titleBox.setSizePolicy(sizePolicy)
        self.titleBox.setObjectName("titleBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.titleBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.titleT = QtGui.QCheckBox(self.titleBox)
        self.titleT.setEnabled(False)
        self.titleT.setChecked(True)
        self.titleT.setObjectName("titleT")
        self.gridLayout_3.addWidget(self.titleT, 1, 2, 1, 1)
        self.titleSizeE = QtGui.QLineEdit(self.titleBox)
        self.titleSizeE.setEnabled(False)
        self.titleSizeE.setObjectName("titleSizeE")
        self.gridLayout_3.addWidget(self.titleSizeE, 2, 1, 1, 1)
        self.titleL = QtGui.QLabel(self.titleBox)
        self.titleL.setObjectName("titleL")
        self.gridLayout_3.addWidget(self.titleL, 1, 0, 1, 1)
        self.titleStatsC = QtGui.QComboBox(self.titleBox)
        self.titleStatsC.setEnabled(False)
        self.titleStatsC.setObjectName("titleStatsC")
        self.titleStatsC.addItem("")
        self.titleStatsC.addItem("")
        self.gridLayout_3.addWidget(self.titleStatsC, 5, 1, 1, 1)
        self.titleE = QtGui.QLineEdit(self.titleBox)
        self.titleE.setEnabled(False)
        self.titleE.setText("")
        self.titleE.setObjectName("titleE")
        self.gridLayout_3.addWidget(self.titleE, 1, 1, 1, 1)
        self.titleEnableC = QtGui.QCheckBox(self.titleBox)
        self.titleEnableC.setText("")
        self.titleEnableC.setObjectName("titleEnableC")
        self.gridLayout_3.addWidget(self.titleEnableC, 0, 1, 1, 1)
        self.titleEnableL = QtGui.QLabel(self.titleBox)
        self.titleEnableL.setObjectName("titleEnableL")
        self.gridLayout_3.addWidget(self.titleEnableL, 0, 0, 1, 1)
        self.titleStatsL = QtGui.QLabel(self.titleBox)
        self.titleStatsL.setObjectName("titleStatsL")
        self.gridLayout_3.addWidget(self.titleStatsL, 5, 0, 1, 1)
        self.titleColorL = QtGui.QLabel(self.titleBox)
        self.titleColorL.setObjectName("titleColorL")
        self.gridLayout_3.addWidget(self.titleColorL, 3, 0, 1, 1)
        self.titleSizeL = QtGui.QLabel(self.titleBox)
        self.titleSizeL.setObjectName("titleSizeL")
        self.gridLayout_3.addWidget(self.titleSizeL, 2, 0, 1, 1)
        self.titleColorB = QtGui.QPushButton(self.titleBox)
        self.titleColorB.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.titleColorB.setPalette(palette)
        self.titleColorB.setText("")
        self.titleColorB.setObjectName("titleColorB")
        self.gridLayout_3.addWidget(self.titleColorB, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.titleBox, 1, 0, 1, 1)
        self.runB = QtGui.QPushButton(self.centralWidget)
        self.runB.setObjectName("runB")
        self.gridLayout_4.addWidget(self.runB, 3, 0, 1, 2)
        self.dirsBox = QtGui.QGroupBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.dirsBox.sizePolicy().hasHeightForWidth())
        self.dirsBox.setSizePolicy(sizePolicy)
        self.dirsBox.setObjectName("dirsBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.dirsBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dirsL = DirsList(self.dirsBox)
        self.dirsL.setAcceptDrops(True)
        self.dirsL.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.dirsL.setDragEnabled(True)
        self.dirsL.setObjectName("dirsL")
        self.gridLayout_5.addWidget(self.dirsL, 0, 0, 1, 2)
        self.dirsSubdirContactsB = QtGui.QCheckBox(self.dirsBox)
        self.dirsSubdirContactsB.setObjectName("dirsSubdirContactsB")
        self.gridLayout_5.addWidget(self.dirsSubdirContactsB, 2, 0, 1, 1)
        self.dirsSubdirImagesB = QtGui.QCheckBox(self.dirsBox)
        self.dirsSubdirImagesB.setObjectName("dirsSubdirImagesB")
        self.gridLayout_5.addWidget(self.dirsSubdirImagesB, 2, 1, 1, 1)
        self.dirsAddB = QtGui.QPushButton(self.dirsBox)
        self.dirsAddB.setObjectName("dirsAddB")
        self.gridLayout_5.addWidget(self.dirsAddB, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.dirsBox, 2, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelEnableL = QtGui.QLabel(self.groupBox)
        self.labelEnableL.setObjectName("labelEnableL")
        self.gridLayout_6.addWidget(self.labelEnableL, 0, 0, 1, 1)
        self.labelEnableC = QtGui.QCheckBox(self.groupBox)
        self.labelEnableC.setText("")
        self.labelEnableC.setObjectName("labelEnableC")
        self.gridLayout_6.addWidget(self.labelEnableC, 0, 1, 1, 1)
        self.labelSizeL = QtGui.QLabel(self.groupBox)
        self.labelSizeL.setObjectName("labelSizeL")
        self.gridLayout_6.addWidget(self.labelSizeL, 1, 0, 1, 1)
        self.labelSizeE = QtGui.QLineEdit(self.groupBox)
        self.labelSizeE.setEnabled(False)
        self.labelSizeE.setObjectName("labelSizeE")
        self.gridLayout_6.addWidget(self.labelSizeE, 1, 1, 1, 1)
        self.labelColorL = QtGui.QLabel(self.groupBox)
        self.labelColorL.setObjectName("labelColorL")
        self.gridLayout_6.addWidget(self.labelColorL, 2, 0, 1, 1)
        self.labelColorB = QtGui.QPushButton(self.groupBox)
        self.labelColorB.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.labelColorB.setPalette(palette)
        self.labelColorB.setText("")
        self.labelColorB.setObjectName("labelColorB")
        self.gridLayout_6.addWidget(self.labelColorB, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 1, 1, 1)
        mc_main.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(mc_main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 657, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        mc_main.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(mc_main)
        self.statusBar.setObjectName("statusBar")
        mc_main.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(mc_main)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_Config = QtGui.QAction(mc_main)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.actionLoad_Config = QtGui.QAction(mc_main)
        self.actionLoad_Config.setObjectName("actionLoad_Config")
        self.menuFile.addAction(self.actionLoad_Config)
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mc_main)
        self.thumbCoverScaleS.setCurrentIndex(2)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), mc_main.close)
        QtCore.QMetaObject.connectSlotsByName(mc_main)

    def retranslateUi(self, mc_main):
        mc_main.setWindowTitle(QtGui.QApplication.translate("mc_main", "Make Contact Sheet(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.sheetBox.setTitle(QtGui.QApplication.translate("mc_main", "Sheet Output Specs", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDirT.setText(QtGui.QApplication.translate("mc_main", "Image Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDirL.setText(QtGui.QApplication.translate("mc_main", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.fileQualL.setText(QtGui.QApplication.translate("mc_main", "Quality :", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOrderC.setItemText(0, QtGui.QApplication.translate("mc_main", "Alphabetical", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOrderC.setItemText(1, QtGui.QApplication.translate("mc_main", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.fileWidthL.setText(QtGui.QApplication.translate("mc_main", "Width :", None, QtGui.QApplication.UnicodeUTF8))
        self.fileQualE.setAccessibleDescription(QtGui.QApplication.translate("mc_main", "File type/extension to use for sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.fileQualE.setText(QtGui.QApplication.translate("mc_main", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOverwriteL.setText(QtGui.QApplication.translate("mc_main", "Overwrite :", None, QtGui.QApplication.UnicodeUTF8))
        self.fileHeightT.setText(QtGui.QApplication.translate("mc_main", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOrderL.setText(QtGui.QApplication.translate("mc_main", "Image Order :", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExtE.setAccessibleDescription(QtGui.QApplication.translate("mc_main", "File type/extension to use for sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExtE.setText(QtGui.QApplication.translate("mc_main", "jpg", None, QtGui.QApplication.UnicodeUTF8))
        self.fileWidthE.setText(QtGui.QApplication.translate("mc_main", "900", None, QtGui.QApplication.UnicodeUTF8))
        self.fileBackgroundL.setText(QtGui.QApplication.translate("mc_main", "Background Color :", None, QtGui.QApplication.UnicodeUTF8))
        self.fileHeightL.setText(QtGui.QApplication.translate("mc_main", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExtL.setText(QtGui.QApplication.translate("mc_main", "File Type (ext) :", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOverwriteC.setItemText(0, QtGui.QApplication.translate("mc_main", "Keep Existing", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOverwriteC.setItemText(1, QtGui.QApplication.translate("mc_main", "Overwrite Existing", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbBox.setTitle(QtGui.QApplication.translate("mc_main", "Thumbnail Specs", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbHeightL.setText(QtGui.QApplication.translate("mc_main", "Height :", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbHeightE.setAccessibleDescription(QtGui.QApplication.translate("mc_main", "File type/extension to use for sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbHeightE.setText(QtGui.QApplication.translate("mc_main", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbBorderL.setText(QtGui.QApplication.translate("mc_main", "Border Width :", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbBorderE.setAccessibleDescription(QtGui.QApplication.translate("mc_main", "File type/extension to use for sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbBorderE.setText(QtGui.QApplication.translate("mc_main", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverModeL.setText(QtGui.QApplication.translate("mc_main", "Cover Mode :", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverModeC.setItemText(0, QtGui.QApplication.translate("mc_main", "No Cover", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverModeC.setItemText(1, QtGui.QApplication.translate("mc_main", "Automatic Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverModeC.setItemText(2, QtGui.QApplication.translate("mc_main", "Explicit File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverL.setText(QtGui.QApplication.translate("mc_main", "Cover File :", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverE.setAccessibleDescription(QtGui.QApplication.translate("mc_main", "File type/extension to use for sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverScaleL.setText(QtGui.QApplication.translate("mc_main", "Cover Scale :", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverScaleS.setItemText(0, QtGui.QApplication.translate("mc_main", "1 Thumb High", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverScaleS.setItemText(1, QtGui.QApplication.translate("mc_main", "2 Thumbs High", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverScaleS.setItemText(2, QtGui.QApplication.translate("mc_main", "3 Thumbs High", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverScaleS.setItemText(3, QtGui.QApplication.translate("mc_main", "4 Thumbs High", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverScaleS.setItemText(4, QtGui.QApplication.translate("mc_main", "5 ThumbsHigh", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbCoverScaleS.setItemText(5, QtGui.QApplication.translate("mc_main", "Full Sheet Width", None, QtGui.QApplication.UnicodeUTF8))
        self.titleBox.setTitle(QtGui.QApplication.translate("mc_main", "Title Specs", None, QtGui.QApplication.UnicodeUTF8))
        self.titleT.setText(QtGui.QApplication.translate("mc_main", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.titleSizeE.setAccessibleDescription(QtGui.QApplication.translate("mc_main", "File type/extension to use for sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.titleSizeE.setInputMask(QtGui.QApplication.translate("mc_main", "999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.titleSizeE.setText(QtGui.QApplication.translate("mc_main", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.titleL.setText(QtGui.QApplication.translate("mc_main", "Title :", None, QtGui.QApplication.UnicodeUTF8))
        self.titleStatsC.setItemText(0, QtGui.QApplication.translate("mc_main", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.titleStatsC.setItemText(1, QtGui.QApplication.translate("mc_main", "Image Size and Counts", None, QtGui.QApplication.UnicodeUTF8))
        self.titleE.setAccessibleDescription(QtGui.QApplication.translate("mc_main", "File type/extension to use for sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.titleEnableL.setText(QtGui.QApplication.translate("mc_main", "Enable:", None, QtGui.QApplication.UnicodeUTF8))
        self.titleStatsL.setText(QtGui.QApplication.translate("mc_main", "Stats :", None, QtGui.QApplication.UnicodeUTF8))
        self.titleColorL.setText(QtGui.QApplication.translate("mc_main", "Color :", None, QtGui.QApplication.UnicodeUTF8))
        self.titleSizeL.setText(QtGui.QApplication.translate("mc_main", "Font Size :", None, QtGui.QApplication.UnicodeUTF8))
        self.runB.setText(QtGui.QApplication.translate("mc_main", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.dirsBox.setTitle(QtGui.QApplication.translate("mc_main", "Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.dirsSubdirContactsB.setText(QtGui.QApplication.translate("mc_main", "Create contacts for Subdirs", None, QtGui.QApplication.UnicodeUTF8))
        self.dirsSubdirImagesB.setText(QtGui.QApplication.translate("mc_main", "Use images from subdirs", None, QtGui.QApplication.UnicodeUTF8))
        self.dirsAddB.setText(QtGui.QApplication.translate("mc_main", "Add ...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mc_main", "Image Label Specs", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEnableL.setText(QtGui.QApplication.translate("mc_main", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeL.setText(QtGui.QApplication.translate("mc_main", "Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeE.setInputMask(QtGui.QApplication.translate("mc_main", "999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeE.setText(QtGui.QApplication.translate("mc_main", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColorL.setText(QtGui.QApplication.translate("mc_main", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mc_main", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("mc_main", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setText(QtGui.QApplication.translate("mc_main", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config.setText(QtGui.QApplication.translate("mc_main", "Load Config", None, QtGui.QApplication.UnicodeUTF8))

from DirsList import DirsList
